server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/angelcntt/microservicios_dia_uno.git
        default-label: main
        search-paths:
        - 'reto-config-service'
#modificado la uri